<a href="https://colab.research.google.com/github/rofikuljoarder2026-creator/Pandas-Project-01/blob/main/Pandas_Project_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
d=pd.read_csv('clean_final_data.csv')
d

,OrderID,CustomerID,OrderDate,ProductID,Quantity,Discount,PaymentMethod,Status,Age,City,SignupDate,CustomerSegment,ProductName,Category,UnitPrice,Sales,OrderValue
0,500001,103695,2025-08-28,2003,4.0,10.0,Gateway,Completed,36.0,Qom,2024-03-05,Regular,USB-C Cable,Accessories,9.0,32.0,32.0
1,500002,107935,2024-05-31,2014,1.0,10.0,Wallet,Completed,49.0,Kerman,2025-06-04,Regular,Backpack,Accessories,42.0,38.0,38.0
2,500003,105141,2025-08-10,2002,1.0,20.0,CardToCard,Completed,36.0,Tehran,2025-10-19,Regular,Mechanical Keyboard,Electronics,62.0,50.0,50.0
3,500004,108780,2024-10-11,2012,1.0,10.0,Gateway,Completed,45.0,Shiraz,2023-12-07,Regular,Office Chair,Home Office,180.0,162.0,162.0
4,500005,101187,2024-02-19,2008,2.0,0.0,Gateway,Completed,24.0,Karaj,2023-12-02,Regular,Phone Case,Accessories,14.0,28.0,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49217,549996,104649,2025-04-30,2013,2.0,5.0,CardToCard,Completed,32.0,Tehran,2025-03-24,Regular,Notebook,Stationery,7.0,13.0,13.0
49218,549997,108686,2025-01-26,2004,1.0,10.0,Gateway,Completed,45.0,Tehran,2024-03-08,New,Power Bank,Electronics,35.0,32.0,32.0
49219,549998,107639,2026-04-13,2010,1.0,0.0,Cash,Completed,56.0,Shiraz,2025-02-19,Regular,Fitness Band,Wearables,55.0,55.0,55.0
49220,549999,108215,2025-04-18,2005,1.0,0.0,CardToCard,Completed,20.0,Qom,2025-08-11,Regular,Laptop Stand,Accessories,28.0,28.0,28.0
49221,550000,102166,2024-04-06,2004,1.0,10.0,Wallet,Completed,62.0,Isfahan,2025-02-01,New,Power Bank,Electronics,35.0,32.0,32.0

In [ ]:
Total_Order=len(d)
print(Total_Order)

49222

In [ ]:
Unique_Customer=d['CustomerID'].nunique()
print(Unique_Customer)

9820

In [ ]:
d['OrderDate']=pd.to_datetime(d['OrderDate'])

In [ ]:
d['SignupDate']=pd.to_datetime(d['SignupDate'])

In [ ]:
d['OrderDate'].dtype

dtype('<M8[us]')

In [ ]:
d['SignupDate'].dtype

dtype('<M8[us]')

In [ ]:
Total_Sales=d['Sales'].sum()
print(Total_Sales)

3444830.0

In [ ]:
Top_Sales_Products=d.groupby('ProductName')['Sales'].agg(['sum','count']).sort_values(by='sum',ascending=False)
print(Top_Sales_Product)

                          sum  count
ProductName
Headphones           333411.0   2559
Office Chair         329292.0   1033
Tablet               292344.0    658
Smart Watch          259590.0   1251
Microphone           230139.0   1539
Mechanical Keyboard  229676.0   2153
Bluetooth Speaker    213311.0   2132
Gaming Controller    198037.0   1663
Power Bank           180004.0   2970
Fitness Band         169860.0   1792
Backpack             169520.0   2293
Webcam               149724.0   1798
Phone Case           122964.0   4977
Desk Lamp            116773.0   2089
Laptop Stand         109879.0   2287
Wireless Mouse        99815.0   3170
HDMI Cable            76020.0   3932
USB-C Cable           74640.0   4700
Notebook              67218.0   5440
Monitor               22613.0    786

In [ ]:
Top_Sales_Product.head()

                   sum  count
ProductName
Headphones    333411.0   2559
Office Chair  329292.0   1033
Tablet        292344.0    658
Smart Watch   259590.0   1251
Microphone    230139.0   1539

In [ ]:
Category_Performance=d.groupby('Category').agg(
    Top_Sales=('Sales','sum'),
    Avg_Discount=('Discount','mean'),
    Total_Quantity=('Quantity','sum')
)
print(Category_Performance)

             Top_Sales  Avg_Discount  Total_Quantity
Category
Accessories   553023.0      7.504261         34524.0
Electronics  1751037.0      7.482128         33030.0
Gaming        198037.0      7.573662          3152.0
Home Office   446065.0      7.381486          5920.0
Stationery     67218.0      7.485294         10331.0
Wearables     429450.0      7.453171          5675.0

In [ ]:
City_Performance=d.groupby('City').agg(
    Unique_Customer=('CustomerID','nunique'),
    Sales=('Sales','sum'),
    Total_Order=('Sales','count')
)
print(City_Performance)

         Unique_Customer     Sales  Total_Order
City
Ahvaz                584  211055.0         2923
Isfahan              949  334531.0         4916
Karaj               1008  350173.0         4966
Kerman               477  175171.0         2465
Mashhad             1278  438112.0         6222
Qom                  481  163150.0         2375
Rasht                558  205882.0         2857
Shiraz               861  310775.0         4363
Tabriz               840  292074.0         4134
Tehran              2784  963907.0        14001

In [ ]:
Payment_Method=d['PaymentMethod'].value_counts()
print(Payment_Method)

PaymentMethod
Gateway       23894
CardToCard    11744
Wallet         8661
Cash           4923
Name: count, dtype: int64

In [ ]:
Order_Status=d['Status'].value_counts()
print(Order_Status)

Status
Completed    45276
Cancelled     2438
Returned      1508
Name: count, dtype: int64

In [ ]:
Customer_Status=d['CustomerSegment'].value_counts()
print(Customer_Status)

CustomerSegment
Regular    27296
New        17056
VIP         4870
Name: count, dtype: int64

In [ ]:
Customer_Order_Status=d.groupby('CustomerSegment').agg(
    Total_Sales=('Sales','sum'),
    Avg_Order_Value=('OrderValue','mean')
)
print(Customer_Order_Status)

                 Total_Sales  Avg_Order_Value
CustomerSegment
New                1196104.0        70.128049
Regular            1914854.0        70.151451
VIP                 333872.0        68.556879

In [ ]:
with pd.ExcelWriter('Final_ECommerce_Business_Report.xlsx') as writer:
    Category_Performance.to_excel(writer, sheet_name='Category Summary')
    City_Performance.to_excel(writer, sheet_name='City Performance')
    Top_Sales_Products.to_excel(writer, sheet_name='Top Products')
    Order_Status.to_excel(writer,sheet_name='Order Status')

print("Report successfully exported to Final_ECommerce_Business_Report.xlsx!")

Report successfully exported to Final_ECommerce_Business_Report.xlsx!